### ISSUE TITLE
Optionally push a tag for `v1.0.x` so you can leverage ^ behaviour on internal repos

### ISSUE THREAD

**Issue by rpocklin** [leonardoanalista/corp-semantic-release#13]
Will add more detail..

**Comment by rpocklin** [comment]
This is not a high priority but may be useful to people who don't use internal NPM repos.

The idea being that you always update the correct 'x' tag for the release so that it always has the latest for `v1.0.x` which can change regularly.  This way you avoid too many updates to your `package.json` for patch releases.

**Comment by leonardoanalista** [comment]
I am not sure if I understand your point. 

> avoid too many updates to your package.json for patch releases

Semantic-release is designed to run on every commit to master in a full automated workflow. Usually there is not problem about many path releases. With semantic-release, release a library is a trivial and fearless task.
