### ISSUE TITLE
Minor: Error message when running from non-release branch is not correct

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#17]
When you run corp-semantic-release with the `-b {branchName}` option, but on a non-releasable branch (e.g. `feature/abc`), the error message says `You can not release from branch other than master. Use option --branch to specify branch name`.

See https://github.com/leonardoanalista/corp-semantic-release/blob/master/index.js#L312

This line should say: `You can not release from branch other than ${releaseBranch}. Use option --branch to specify branch name`.

**Comment by leonardoanalista** [comment]
Thank you. I ll fix this when I return.
