### ISSUE TITLE
update changelog version to 1.x

### ISSUE THREAD

**Issue by leonardoanalista** [leonardoanalista/corp-semantic-release#2]
Those warnings should be gone:

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
corp-semantic-release@ /home/vagrant/aaprojects/ib-refresh/corp-semantic-release

**Comment by leonardoanalista** [comment]
@uglow finally made the updates. As it updates major underlying library, just to be in the safe side, I made a major version. Unit tests were unchanged. So behaviour changes have been detected in the unit tests.

**Comment by uglow** [comment]
@leonardoanalista Just saw this. Will update Confit to use this version. Thanks Leo

**Comment by leonardoanalista** [comment]
No worries, I mean "**NO** behaviour changes have been detected in the unit tests." rather than "**So** behaviour....
