### ISSUE TITLE
Specify the Release Count

### ISSUE THREAD

**Issue by nick-woodward** [leonardoanalista/corp-semantic-release#23]
### Problem

I'm storing my `CHANGELOG.md` on a `latest` branch to 
keep my built code separate from my source code.

At the same time I have a `CHANGELOG.md` in my `master` branch 
that points to the `CHANGELOG.md` on the `latest` branch.

This means that the `CHANGELOG.md` file on the latest branch gets 
overriden with the `master` version.

So when `corp-semantic-release` runs it ends up appending the 
latest version to a bogus `CHANGELOG.md` file

Instead, I would like `corp-semantic-release` to allow me to override 
the releaseCount option that gets passed to `conventional-changelog`

### Solution

[Related File](https://github.com/leonardoanalista/corp-semantic-release/blob/master/src/index.js#L72-L74)
```js
var options = {
  preset: program.changelogpreset
  releaseCount: program.releaseCount
};
```

### Related Links

- [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog-cli/blob/master/cli.js#L85-L93)

**Comment by uglow** [comment]
Are you able to provide more information about this requirement? Eg:
Problem:
Proposed solution:
Workarounds?

**Comment by nick-woodward** [comment]
Sorry about that, I was in a bit of a rush when I opened the issue.

Updated with a bit more information as well as a solution.

Also included a link to how `conventional-changelog-cli` solves this.

**Comment by uglow** [comment]
@nick-woodward - please review https://github.com/leonardoanalista/corp-semantic-release/pull/24
