### ISSUE TITLE
Exit 0 when branch is not master branch

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#38]
`corp-semantic-release` exits with 1 when the current branch is not the master branch.

https://github.com/leonardoanalista/corp-semantic-release/blob/master/src/lib/validateBranch.js#L12

To support git-flow style workflow, feature branches should be able to pass all tests and have a successful build before code can be merged onto the master branch. Ideally, there should be no difference between the build-script on master and the build script on a branch. (In fact, this module is designed to detect this situation itself.)

So what should happen is this:
- `corp-semantic-release` detects that it is not on master and returns 0
- if any scripts should only be executed on successful release of code, they should be passed as an argument to the `--post-success` flag (new in v4)

By doing this, feature-branches could build successfully while not releasing or publishing code.

**Comment by uglow** [comment]
@leonardoanalista thoughts?

**Comment by leonardoanalista** [comment]
It sounds good. Keep in mind some places may release from `develop` branch. Semantic-release implies less master and feature branches and I think less branches is less to think about it.
