### ISSUE TITLE
The command should fail if post-success fails

### ISSUE THREAD

**Issue by mlazowik** [leonardoanalista/corp-semantic-release#40]
To reproduce try running with `--post-success "gibberish"`.

This is important, because otherwise your ci builds will succeed even if, for example, `npm publish` fails.

**Comment by leonardoanalista** [comment]
Hi Michal, Fyi this is the PR which introduced the `post-success` as normal script, not necessarily npm script.
https://github.com/leonardoanalista/corp-semantic-release/pull/36/files
