### ISSUE TITLE
Allow publishing from any branch via the use of --any-branch

### ISSUE THREAD

**Issue by enriquecaballero** [leonardoanalista/corp-semantic-release#43]
Setting a branch name via `--branch` is a bit difficult with Jenkins, since Jenkins doesn't really checkout a specific branch, but checks out a revision. We currently use `standard-version` for our builds, and it works great. However, we would like to switch over to `corp-semantic-release` because of the sweet verification step as to whether or not it should actually make release. Thoughts?

**Comment by leonardoanalista** [comment]
Corp-sem-release and semantic-release work well when you always release from master. The option --branch was created for some places where they release from "developer" branch or equivalent. 
We can easily create a new option --any-branch for those cases like yours. 
This could be a couple of lines PR. 
I might be able to add it tonight or tomorrow if I have time. If you would like to do, just let me know so we don't duplicate efforts. 
Cheers Leo

**Comment by leonardoanalista** [comment]
Hi @enriquecaballero review this PR. It will allow you to release from any branch if you specify option `--any-branch`. Be aware `--any-branch` takes precedence over `--branch`.
There is no breaking change, just a new feature. Thanks for the suggestion!
Leonardo

**Comment by enriquecaballero** [comment]
Looks good to me, man. That was quick!

**Comment by leonardoanalista** [comment]
No problems, I'll merge as soon as Brett (repo maintainer) has a chance to look at this too. Otherwise I merge early Tuesday. Monday is a public holiday in Australia.
