### ISSUE TITLE
Add [ci skip] to release message for CI servers

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#45]
Some CI servers (e.g. [Travis](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build), [CircleCI](https://circleci.com/docs/1.0/skip-a-build/), [Concourse](https://github.com/concourse/git-resource#behavior)) support a scheme whereby if a commit message contains the string `[ci skip]`, the commit does not trigger another build. This would be useful to add to the release commit message produce by corp-semantic-release, to avoid release-commits triggering rebuilds.

**Comment by leonardoanalista** [comment]
It sounds good to me. I wonder if all CI's would use the same `[ci skip]` text.

If not, we could have a mapping of 
```
const ciSkipBuild = {
  travis: '[ci skip]',
  circleci: '[ci skip]',
  jenkins: '[ci skip]',
}
```

**Comment by leonardoanalista** [comment]
It seems like `[ci skip]` is unanimous: https://github.com/banyan/jenkins-ci-skip-plugin

**Comment by azz** [comment]
TeamCity supports configuring commit message filters, so `[ci skip]` should be workable there, too.

VCS trigger rule:

```
-:comment=\[ci skip\]:**
```
