### ISSUE TITLE
Doesnot update package-lock.json

### ISSUE THREAD

**Issue by svuppala** [leonardoanalista/corp-semantic-release#47]
I am not sure if this is the right channel to raise this issue.We are using this module with npm@5 and noticed this module doesn't bump up version in package-lock.json.

Does npm-version supports package-lock.json?

**Comment by leonardoanalista** [comment]
That's fine here. I haven't tested on npm5. 

Did you notice if you see console messages `>>> update version on package.json...` from [line](https://github.com/leonardoanalista/corp-semantic-release/blob/master/src/lib/bumpUpVersion.js#L8)?

Maybe run with option `--verbose` and `-d` for a dry run.

**Comment by svuppala** [comment]
It is updating package.json but not package-lock.json

Log:--------

>> Your release branch is: integration 
build	24-Aug-2017 10:24:29	>>> Bump type is patch
**build	24-Aug-2017 10:24:29	>>> update version on package.json...** 
build	24-Aug-2017 10:24:30	v1.2.1
build	24-Aug-2017 10:24:30	>>> About to add and commit package.json and CHANGELOG...

**Comment by leonardoanalista** [comment]
it should happen automatically here is the according to official docs: https://docs.npmjs.com/files/package-lock.json

Please try to run manually `npm version v9.9.9`, then second test case `npm version --no-git-tag-version v9.9.9`. That's what this module does under the cover.

**Comment by svuppala** [comment]
npm version --no-git-tag-version v9.9.9 worked fine.Can you test with npm 5?

I have also tried pre-commit options and didnot work.

    "corp-release": "corp-semantic-release --pre-commit updateFiles --changelogpreset angular-bitbucket --branch integration",
    "updateFiles": "node package-lock.json && git add package-lock.json",

**Comment by leonardoanalista** [comment]
With the last command you ran, did that update package-lock.json too? 
If not, this might be the default behavior of npm5. 
Can you explain why package-lock.json must be updated? This file is to lock dependency, not your own package version as far as I understand.

**Comment by svuppala** [comment]
Yes the last command updated the package-lock.json.

**Comment by leonardoanalista** [comment]
Sorry this line https://github.com/leonardoanalista/corp-semantic-release/blob/master/src/lib/bumpUpVersion.js#L14
actually does something like this: 
`npm version --no-git-tag-version patch`. Can you test this?

**Comment by svuppala** [comment]
Yes ...tested it and it updated both package.json and package-lock.json.

**Comment by svuppala** [comment]
We have fixed this issue with --pre-commit [npm-script]

"corp-release": "corp-semantic-release --pre-commit update-version --changelogpreset angular-bitbucket --branch integration",
    "update-version": "node update-version.js",

**Comment by leonardoanalista** [comment]
cool!
