### ISSUE TITLE
Version is bumped even when there are no changes

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#5]
New repo **without a remote**.

Initial output:
```console
Bretts-MBP:test-app brettuglow$ npm run semantic-release

> test-app@0.0.0 semantic-release /code/yo/test-app
> corp-semantic-release

>> No SemVer tag found. It seems like your first release? 
>>> Bump type is minor
>>> update version on package.json...
v0.1.0
>>> About to add and commit package.json and CHANGELOG... 
>> Time to create the Semantic Tag: v0.1.0 
[master def4489] chore(release): v0.1.0
 2 files changed, 18 insertions(+), 2 deletions(-)
 create mode 100644 CHANGELOG.md
>>...and push to remote... 
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>
```

Subsequent output:
```console
> test-app@0.1.0 semantic-release /code/yo/test-app
> corp-semantic-release

>> No SemVer tag found. It seems like your first release? 
>>> Bump type is minor
>>> update version on package.json...
v0.2.0
>>> About to add and commit package.json and CHANGELOG... 
>> Time to create the Semantic Tag: v0.2.0 
[master e3f0fa4] chore(release): v0.2.0
 2 files changed, 7 insertions(+), 1 deletion(-)
>>...and push to remote... 
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

```

Git Log:
```
Bretts-MBP:test-app brettuglow$ git log
commit 22e3db7ee86b14807d665fd889afc7f7b8dfbae9
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:12:17 2016 +1100

    chore(release): v0.4.0

commit b76329b5d80b1cb18613d502e466a4e50908c7e3
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:12:04 2016 +1100

    chore(release): v0.3.0

commit ddbaa36e82eed0345a97d438fea6241da091965e
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:11:03 2016 +1100

    docs(accounts): readme

commit e3f0fa47049ac3772118d68330545e3537af42c6
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:06:34 2016 +1100

    chore(release): v0.2.0

commit def448978c1604e6b78f9f5f721fd267fa80aa47
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:05:15 2016 +1100

    chore(release): v0.1.0

commit d4c738934c5a6e14756c24f22d8a8154af88768d
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 11:00:40 2016 +1100

    fix(exampleScope): add extra config

commit 32409f4b9987261a891deb96fd6fd218aec4198f
Author: Brett Uglow <buglow@odecee.com.au>
Date:   Wed Mar 30 10:59:49 2016 +1100

    feat(accounts): commit 1
```

CHANGELOG.md:
<a name="0.4.0"></a>
# [0.4.0](/https://example.com/entity/repo/compare/v0.3.0...v0.4.0) (2016-03-30)

<a name="0.3.0"></a>
# [0.3.0](/https://example.com/entity/repo/compare/v0.2.0...v0.3.0) (2016-03-30)

<a name="0.2.0"></a>
# [0.2.0](/https://example.com/entity/repo/compare/v0.1.0...v0.2.0) (2016-03-30)

<a name="0.1.0"></a>
# 0.1.0 (2016-03-30)

### Bug Fixes

* **exampleScope:** add extra config ([d4c7389](https://example.com/entity/repo/commits/d4c7389))

### Features

* **accounts:** commit 1 ([32409f4](https://example.com/entity/repo/commits/32409f4))

**Comment by leonardoanalista** [comment]
please have a look at the added tests: https://github.com/leonardoanalista/corp-semantic-release/pull/6/files#diff-1098cf96025316f5f8ec5e4b373d016fR123

There has been no meaningful source code changes on `index.js`. Tests perform the same manual steps you did. I am not sure why you had the changelog and package.json modified. Is there any additional steps you did after the first version `0.1.0`?

**Comment by leonardoanalista** [comment]
there is actually something wrong. Tests pass in my machine but fail in Travis. I'll have a look now

**Comment by leonardoanalista** [comment]
I figured out. I cleaned up some dependencies and one of them was `git-latest-semver-tag`. It was pruned from my local node_modules but it was found in my global npm path. Now I included as a dependency. It should be fixed in a few minutes.

**Comment by leonardoanalista** [comment]
At least now we have tests to detect situations where we run multiple times and no changes are expected. I still need to now how to avoid npm o look at the global so this won't happen again.

**Comment by uglow** [comment]
I'll try it in a few hours. Thanks Leo
