### ISSUE TITLE
Problems while using in Bitbucket

### ISSUE THREAD

**Issue by gund** [leonardoanalista/corp-semantic-release#53]
Hi!
First of all - thanks a lot for creating this awesome alternative of semantic-release.

Recently I've came to the need to integrate a tool same as `semantic-release` but in private Bitbucket repo and so I ended up here =)

I tried to use it but stuck with this error:
```bash
$ corp-semantic-release --changelogpreset angular-bitbucket
/bin/sh: git: not found
/bin/sh: git: not found
You can only release from the master branch. Use option --branch to specify branch name.
```
But my CI pipeline actually runs on master branch, this is the command from logs used to clone repo: `git clone --branch="master"`
And you can notice also it complains about git not being found which is strange...

I also tried to specify `--branch *` to bypass check (found in source code) but got really weird result:
```bash
$ corp-semantic-release --changelogpreset angular-bitbucket --branch *
/bin/sh: git: not found
/bin/sh: git: not found
You can only release from the README.md branch. Use option --branch to specify branch name.
```
As you can see that is really some crazy result and I just have no idea what I'm doing wrong...

Will appreciate any help.

Thanks again

**Comment by gund** [comment]
Okay so the problem was basically because I was running on the node-alpine image which does not have git installed so I simply switched to full node image and it fixed the issue.

Thanks for easy to use library!

**Comment by leonardoanalista** [comment]
Hi Alex, I am glad you solved the problem before I even had a chance to read the issue. Cheers 👍
