### ISSUE TITLE
Add ***NO_CI*** to release message for VSTS skip build

### ISSUE THREAD

**Issue by marceloavf** [leonardoanalista/corp-semantic-release#54]
VSTS triggers work different from others scheme like Travis, CircleCI, etc. It requires the `***NO_CI***` in the end of the message to skip the build, so `[ci skip]` doesn't seems to work

**How do I avoid triggering a CI build when the script pushes?**
```
Add ***NO_CI*** to your commit message. For example, git merge origin/features/hello-world -m "Merge to master ***NO_CI***"
```
[Documentation ](https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/git-commands)

**Comment by marceloavf** [comment]
This will not stop **Travis** and others CI since this allow it to be anywhere in the commit messages, will only add support for VSTS (Visual Studio Team Services) from Microsoft

**Comment by leonardoanalista** [comment]
No worries, I’ll review this pr tomorrow for sure
