### ISSUE TITLE
after_success with Travis CI don't run.

### ISSUE THREAD

**Issue by humatios** [leonardoanalista/corp-semantic-release#57]
I want that after the successful completion of the **Travis CI** build (_after_success_), in the _Master branch_ run "npm run corp-release", but the following message appears:
```
* (HEAD detached at commit_id)
  master
HEAD
You can only release from the master branch. Use option --branch to specify branch name.
```

So, i don't know if that is a good way to do my _Release_. But, is not working for me from **Travis CI**.

**Comment by leonardoanalista** [comment]
Ideally you should release from master but If you really don’t want to do that,
Use —branch [branch name] or option —any to release from any branch. 

There are lots of benefits when you use master as release branch but is is up to you.

**Comment by humatios** [comment]
I release from Master, but from Travis CI.
But when Travis executes the command _corp-release_ it does not detect that Travis is in the Master branch. (Travis is configured to run only with the changes in Master branch)

**Comment by leonardoanalista** [comment]
I can see `HEAD detached`. Maybe Travis is in a middle of conflict. I usually get this situation in the middle of a rebase. I am not quite sure how to address this issue.

**Comment by StephanGerbeth** [comment]
Sorry, that i must reopen this ticket, but i have the same problem. Locally it is working, but when i try to run it at travis, i get the same error: 

`You can only release from the master branch. Use option --branch to specify branch name.`

i tried the following commands:
```
corp-semantic-release
corp-semantic-release --branch *
corp-semantic-release --branch master
```
with the same result. Please help!
