### ISSUE TITLE
Release a pre-release version with tag .beta in package.json

### ISSUE THREAD

**Issue by marceloavf** [leonardoanalista/corp-semantic-release#58]
Is there a way to make a release come with some `1.0.0-beta` ?

**Comment by tmosest** [comment]
or could we add the tag template from semantic-release?

tagFormat
Type: String

Default: v${version}

CLI arguments: -t, --tag-format

The Git tag format used by semantic-release to identify releases. The tag name is generated with Lodash template and will be compiled with the version variable.

Note: The tagFormat must contain the version variable exactly once and compile to a valid Git reference.

**Comment by tmosest** [comment]
Here is the little bit of code it took me to add a prefix, you can use this to add your suffix or just use a prefix instead.

https://github.com/tmosest/corp-semantic-release/commit/ef5d8961046a25148eb1e1d03140ffa248195801

**Comment by leonardoanalista** [comment]
it looks good to me. I would merge if it was in a PR.

**Comment by tmosest** [comment]
@leonardoanalista if you give me access to push up to feature branches, I'll fix it up to use templates instead of just prefixs and put in a PR for it. I'd rather upgrade your repo than keep my own fork of it.

**Comment by leonardoanalista** [comment]
You should be able to push now. Let me know if you still have issues

**Comment by tmosest** [comment]
Hey @leonardoanalista tried to push up a feature branch and got permission denied.

**Comment by leonardoanalista** [comment]
I canceled and re-sent the invitation. I added you as collaborator 👍
