### ISSUE TITLE
First release version

### ISSUE THREAD

**Issue by MkMan** [leonardoanalista/corp-semantic-release#61]
When running corp-semantic-release for the first time, it doesn't increment the version based on what's in package,json, instead it resets it to version 1.0.0.

**Comment by leonardoanalista** [comment]
That’s the intended behavior. This aligns with semantic-release as far as I remember.

**Comment by MkMan** [comment]
Thanks for getting back to me quickly.

Fair enough. So we've been working on an npm module and have been manually incrementing its version. We'd like to start using corp-semantic-release but because of this behaviour it will reset us back to v1.0.0 which will cause us problems. What's the best approach in this situation ?

**Comment by leonardoanalista** [comment]
The idea behind semantic-release and Corp-semantic-release is to automate the version number so you never set the version manually. This number allocation is based on your strstured commit messages since the last semver tag. Then the tool decides if bump is a patch, minor or major, again it s all based on commit messages. 
If you really want to set the version manually, sorry tools mentioned here are not suitable for your case.

**Comment by MkMan** [comment]
I think I explained the situation poorly. 

We started a project **without** using semantic release and had been incrementing the version manually.
We are now up to v1.5.0
We would like to start using semantic release to automate the versioning. We **don't** want to increment the version manually any more.

The concern we have is upon using it for the first time it will set us back to v1.0.0 which we don't want. Is there a way to make its first release match/use our current package.json version?

**Comment by leonardoanalista** [comment]
You probably incrementes version by changing in the package.json only and never created a tag to match the version. If that’s what you did, all you need to to is create a semver tag to match what you have now, then corp-semantic-release will know how to increment.

**Comment by leonardoanalista** [comment]
I m on mobile now. In one hour, I’ll look at the code to tell you the npm command to run. It may be just “giy tag v1.5.0” with the “v” or not, I don’t remember now

**Comment by MkMan** [comment]
Awesome! Thanks for your help. I've been looking into this and the tags have a "v" at the start. Thanks again

**Comment by veroca** [comment]
ahhh now I get what was happening to me as well. Thank you both for the clarification. Perhaps a comment about this in the README would be very useful :) 
Great tool Leo.
