### ISSUE TITLE
No SemVer tag found

### ISSUE THREAD

**Issue by rodoabad** [leonardoanalista/corp-semantic-release#63]
```
>>> Your release branch is: master 
>> No SemVer tag found. It seems like your first release? Initial release will be set to v1.0.0 as per npmjs specification. 
```

I keep getting this when it's running on CI. Is there a reason why it can't see the tags?

**Comment by leonardoanalista** [comment]
Hi Rodo, What happened and how did you solve it? just curious.

**Comment by rodoabad** [comment]
@leonardoanalista one thing to note is I am using Jenkins for my CI.

Jenkins normally checkouts a specific hash.

```groovy
        stage('Release') {
            when {
                allOf {
                    branch 'master'
                    expression { GIT_COMMIT != GIT_PREVIOUS_SUCCESSFUL_COMMIT }
                }

            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-token', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh('git checkout ${GIT_BRANCH}')
                    sh('git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.my-domain.com/github-org/repository.git')
                    sh('git pull --tags')
                    sh('npx corp-semantic-release')
                }
                sh('npm publish')
            }
        }
```

The only problem here is that `npm publish` will run even if there's no new version to publish. I'm still working on that solution.

**Comment by rodoabad** [comment]
@leonardoanalista if you notice I'm also setting the remote URL with the credentials which solve the problem I was having in https://github.com/leonardoanalista/corp-semantic-release/issues/62#issuecomment-404681323.

**Comment by rodoabad** [comment]
@leonardoanalista it's also a little weird that my commit messages are `chore(release): v1.0.6 [ci skip] ***NO_CI***` even though I'm doing it in a CI environment.

**Comment by rodoabad** [comment]
I just realized you can do `--post-success "npm publish`
