### ISSUE TITLE
CI option

### ISSUE THREAD

**Issue by Biboba** [leonardoanalista/corp-semantic-release#66]
Hello,

I would like the release to trigger CI as in my worklow, the CI is actually generating the artifacts of the release.
It would be nice to have a CI option in order to trigger CI or not just like semantic-release offer:
https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#ci
It would then either add "[ci skip] ***NO_CI***" or not.

I believe so far it is not possible ?

Thanks

**Comment by leonardoanalista** [comment]
Yes, this is possible. We could follow the same API. It would be great to know what they do under the cover, if they add a text `[ci skip]` to the commit message. I guess so but it is good to confirm. Btw feel free to send a PR if you have a chance.

**Comment by Biboba** [comment]
Hello,

Thanks for the reply. I will have a look then and send PR.
