### ISSUE TITLE
Bug: If package.json does not contain a version, tool does not work

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#8]
In testing, for some reason I ended up with a `package.json` file that did not have any name, version or description in it. Before I noticed that, I ran `corp-semantic-release` which produced this output:

```console
> corp-semantic-release

v0.4.0
>>> Bump type is major
>>> update version on package.json...
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease]
npm ERR! (run in package dir)
npm ERR! 'npm -v' or 'npm --version' to print npm version (2.14.12)
npm ERR! 'npm view <pkg> version' to view a package's published version
npm ERR! 'npm ls' to inspect current package/dependency versions
>>> About to add and commit package.json and CHANGELOG... 
>> Time to create the Semantic Tag:  
v0.1.0
v0.2.0
v0.3.0
v0.4.0
[master 236ffb7] chore(release):
 1 file changed, 15 insertions(+)
>>...and push to remote... 
```

Using a `package.json` with a version, name and description fixed this. 

Perhaps the tool can identify it's mandatory fields in the package.json and either warn/error/fix the problem?

**Comment by leonardoanalista** [comment]
As fas as I remember, version and name are required. The rest are optional. I assume npm users know that. Despite of that, I am going to add this validation in order to avoid unpredictable results.

**Comment by leonardoanalista** [comment]
Validation for fields version and name in the package.json ad been added on version 1.2.0 as per commit https://github.com/leonardoanalista/corp-semantic-release/commit/ca104bea. 
I forgot to link this issue at that stage.
