### ISSUE TITLE
Should the tag be on the release-commit?

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#9]
Hi @leonardoanalista,

Just wondering whether the tag should be on the release commit, rather than on the previous commit.
<img width="323" alt="screen shot 2016-04-06 at 1 08 58 pm" src="https://cloud.githubusercontent.com/assets/3990189/14304720/c672f086-fbf8-11e5-8364-3c378046bbfc.png">

Thoughts?

**Comment by leonardoanalista** [comment]
Brett

Semantic-release uses Github API v3 to create a release. In this case there is no file changes, therefore nothing to commit. Just a git tag to push to remote.

This module creates/appends to a CHANGELOG.md. This file is updated on every release and needs to be committed. 

There will be support to Github API v3 down on the road.

thanks for the issue anyway.

Leo

**Comment by uglow** [comment]
In the attached picture, the commit with the message "chore(release) v0.3.0" is NOT the commit with the tag "v0.3.0". 

I'm not suggesting that the solution is to use the Github API, only that the tag-step occur AFTER the commit-step. That way, the "chore(release) v0.3.0" commit would also have the "v0.3.0" tag.

**Comment by leonardoanalista** [comment]
ok it makes sense. Reopening this issue.
Just to clarify: If /when we use Github Api v3 to create a `release`, there will be no need for this extra commit "chore(release) vxzy".
Plan is to support both ways for a period of time.

**Comment by uglow** [comment]
I'll try and look at this now...
